backend:
  name: git-gateway
  branch: main
media_folder: "images"
collections:
  - name: "avis"
    label: "Avis"
    folder: "avis"
    create: true
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Message", name: "message", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }